name: 'Setup'
description: 'Setup project and run db'
runs:
  using: 'composite'
  steps:
    - uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2

    - run: npm install @openapitools/openapi-generator-cli -g
      shell: bash

    - run: cargo install sqlx-cli
      shell: bash

    - run: docker compose up -d db
      shell: bash

    - run: cp .env.example .env
      shell: bash

    - run: make reset-db
      shell: bash

    - run: make generate-schema
      shell: bash
