name: 'Setup'
description: 'Setup project (toolchain, cache, OpenAPI schema)'
runs:
  using: 'composite'
  steps:
    - uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "rust-cache"

    - run: npm install @openapitools/openapi-generator-cli -g
      shell: bash

    - run: cp .env.example .env
      shell: bash

    - run: make generate-schema
      shell: bash
