services:
  # api:
  #   build:
  #     context: agon_service
  #   container_name: poem_api
  #   ports:
  #     - 7000:7000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 7001:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7002:808

  # ui:
  #   build:
  #     context: agon_ui 
  #   container_name: poem_api
  #   ports:
  #     - 7003:80
  #   restart: unless-stopped
