version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 7001:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7002:8080
