on:
  workflow_call:
    inputs:
      agon-service-image:
        required: true
        type: string
      agon-ui-image:
        required: true
        type: string
      stack-name:
        required: true
        type: string
    outputs:
      agon-url:
        value: ${{ jobs.deploy.outputs.agon-url }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: agon_infra

    environment:
      name: ${{ inputs.stack-name }}
      url: https://${{ steps.pulumi-up.outputs.agonDomain }}

    outputs:
      agon-url: https://${{ steps.pulumi-up.outputs.agonDomain }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - run: pnpm install

      # TODO Maybe only build a new image if there is a change to the code?
      - name: Update agon image in pulumi stack config
        run: >
          pulumi stack select ${{ inputs.stack-name }}
          && pulumi config set agonServiceImage ${{ inputs.agon-service-image }}
          && pulumi config set agonUiImage ${{ inputs.agon-ui-image }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'agon_infra/Pulumi.${{ inputs.stack-name }}.yaml'
          message: '{{ input.stage-name }} release\n agon-service-image ${{ inputs.agon-service-image }}\nagon-ui-image ${{ inputs.agon-ui-image }}'

      - uses: pulumi/actions@v6
        id: pulumi-up
        with:
          command: up
          stack-name: ${{ inputs.stack-name }}
          work-dir: ./agon_infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

