on:
  workflow_call:
    outputs:
      image:
        description: 'Full container image reference with tag'
        value: ${{ jobs.docker-push.outputs.image }}

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
    outputs:
      image: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: cargo sqlx prepare
        working-directory: ./agon_service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/jelgar/agon_service
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./agon_service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
