name: PR

on:
  pull_request:

jobs:
  build-service:
    uses: JElgar/agon/.github/workflows/build-service.yml@main
    secrets: inherit

  build-ui:
    uses: JElgar/agon/.github/workflows/build-ui.yml@main
    secrets: inherit
