name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: JElgar/agon_service/.github/workflows/build.yml@main
    secrets: inherit

  publish:
    needs: build
    uses: JElgar/agon_service/.github/workflows/docker.yml@main
    secrets: inherit

  deploy:
    needs: publish
    uses: JElgar/agon_service/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      agon-image: ${{ needs.publish.outputs.image }}
      stack-name: staging
