name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build-service:
    uses: JElgar/agon/.github/workflows/build-service.yml@main
    secrets: inherit

  build-ui:
    uses: JElgar/agon/.github/workflows/build-ui.yml@main
    secrets: inherit

  publish-service:
    needs: build-service
    uses: JElgar/agon/.github/workflows/docker-service.yml@main
    secrets: inherit

  publish-ui:
    needs: build-ui
    uses: JElgar/agon/.github/workflows/docker-ui.yml@main
    secrets: inherit

  deploy:
    needs: [publish-service, publish-ui]
    uses: JElgar/agon/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      agon-service-image: ${{ needs.publish-service.outputs.image }}
      agon-ui-image: ${{ needs.publish-ui.outputs.image }}
      stack-name: staging

  test:
    needs: deploy
    uses: JElgar/agon/.github/workflows/test.yml@main
    with:
      agon-service-url: ${{ needs.deploy.outputs.agon-service-url }}
    secrets:
      jwt-secret: ${{ secrets.SUPABASE_STAGING_JWT_SECRET }}
