name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: JElgar/agon_service/.github/workflows/build.yml@main
    secrets: inherit

  publish:
    needs: build
    uses: JElgar/agon_service/.github/workflows/docker.yml@main
    secrets: inherit

  deploy:
    needs: publish
    uses: JElgar/agon_service/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      agon-image: ${{ needs.publish.outputs.image }}
      stack-name: staging

  test:
    needs: deploy
    uses: JElgar/agon_service/.github/workflows/test.yml@main
    with:
      agon-service-url: ${{ needs.deploy.outputs.agon-service-url }}
    secrets:
      jwt-secret: ${{ secrets.SUPABASE_STAGING_JWT_SECRET }}
